### PR TITLE
make progress stop when block stops

### PR DESCRIPTION
**Pull request by grosser**
replaces https://github.com/grosser/kennel/pull/203

@zdrve

### CODE REVIEW

**Comment by zdrve** [comment]
It's not as watertight as my PR, but it'll help most of the time, I'll give you that.

**Comment by grosser** [comment]
I'm not aware of any edge-case or bug that is not addressed, can you elaborate ?

**Comment by zdrve** [comment]
```
         break if stop
                         # <- the other thread calls 'thread.run' here
          Kennel.err.print animation[count % animation.size]
                         # <- or here
          sleep interval
```

in which case the `.run` won't wake up the thread, because it hasn't slept yet.

**Comment by grosser** [comment]
yeah true, good catch :)
0.0x% chance that we lose 0.2s so should be fine :)

**Comment by grosser** [comment]
found 1 more race condition that could crash the progress https://github.com/grosser/kennel/pull/205

**Pull request merged**
