### PR TITLE
Allow setting notify_audit

### PR DESCRIPTION
**Pull request by tancnle**
### Description

Allow setting `notify_audit` option when setting up monitor.

### CODE REVIEW

**Comment by grosser** [comment]
please add a test too, atm this does not work since it's not used in https://github.com/tancnle/kennel/blob/313eeda81b182379ebbdcfcf73c31513a5fd3097/lib/kennel/models/monitor.rb#L52
https://github.com/grosser/kennel/pull/25 is a good example

**Comment by tancnle** [comment]
💇‍♂️ @grosser

**Comment by grosser** [comment]
🔥

**Comment by grosser** [comment]
1.8.2

**Pull request merged**
